### ISSUE TITLE
How to update YourPlugin.md

### ISSUE THREAD

**Issue by b-morgan** [OllisGit/OctoPrint-KnowledgeBase#1]
On the wiki page https://github.com/OllisGit/OctoPrint-KnowledgeBase/wiki/PluginPython23 you mention YourPlugin.md but don't say much about how to update it.

I'm a complete GIT beginner and while I muddled through the initial registration of my plugin in the repository, I seem to be unable to figure out how to update my FanSpeedMirror.md once I add the
 ```
compatibility:
  python: ">=2.7,<4"
```
Pushing and Pulling are so confusing to me. I'm much more comfortable with SVN (or CVS).

Any chance you could enhance your wiki to show the steps involved?

**Comment by OllisGit** [comment]
Hi @b-morgan,
you can find a description about distribution a plugin in this wiki-page: https://github.com/OllisGit/OctoPrint-KnowledgeBase/wiki/DistributePlugin
I will update this page about the Python3 related stuff.

There is a description how to update/create the ```YourPlugin.md```.

In your case you could skip some steps, because you have already a fork of the plugin-repository in your git account.
The first think to do is that you bring your repository (https://github.com/b-morgan/plugins.octoprint.org) up to date with the op-repository. 
Look into this message: 

> This branch is 3 commits ahead, 309 commits behind OctoPrint:gh-pages.

Unfortunately you already did some commits (3x). If you follow my description these three commits will be lost....just add these changes after the ```git push --force``` and then push your changes again to your repo. 
Then you can create a merge-Request via the GitHub-UI.

Btw. if you add only some small changes to the current existing page, it is not necessary to install/build Jekyll. It is just a local build verification.

Hope this helps...if you have further questions/improvements your welcome.

**Comment by b-morgan** [comment]
Gina posted [this](https://community.octoprint.org/t/documentation-migrating-to-python-3-error-after-following-note-instructions/17817/11?u=b-morgan) and I was able to update FanSpeedMirror.md. 

I believe I no longer need a forked copy of http://plugins.octoprint.org/ so rather than figure out how to get my fork synced with the official repository, I just deleted my fork! Bottom line is I believe there are two procedures that require documentation. 

First, how to add a new plugin.md file to http://plugins.octoprint.org/. I believe Gina has documented this one.

Second, how to update an existing plugin.md file in http://plugins.octoprint.org/. I believe Gina's post linked above is the beginning of this documentation.

**Comment by OllisGit** [comment]
Thx, I didn't read that post. 

It could be easier to use the GitHub-UI for creating and updating single existing plugin.md-file.
Updating is shown in the post and creating is also done view UI-Button:
![image](https://user-images.githubusercontent.com/24205767/78401976-20c0c700-75fa-11ea-86a7-828e630e5ed2.png)

But I stay on the "fork-approach", because then I can change a couple of things in one Pull-Request.
